### ISSUE TITLE
The distillation loss problem

### ISSUE THREAD

**Issue by wanghangege** [Serenos/DI-V2X#1]
![image](https://github.com/Serenos/DI-V2X/assets/51116270/d50b7adf-30b5-47ab-b2c0-e73b96963bde)
Hello, excellent researcher. Through reading your paper, there is a formula I don't understand. It's about the understanding of m and n as figure. The former summation subscript is m and m, and the latter summation subscript is m and n. How should I understand it? It seems that it is not given in the article.

**Comment by Serenos** [comment]
Sorry for the mistake, the former summation subscript should be m and n. I'll fix that in the final version. Thanks.







| |
Lixiang
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/28/2024 10:14 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [Serenos/DI-V2X] The distillation loss problem (Issue #1) |

image.png (view on web)
Hello, excellent researcher. Through reading your paper, there is a formula I don't understand. It's about the understanding of m and n as figure. The former summation subscript is m and m, and the latter summation subscript is m and n. How should I understand it? It seems that it is not given in the article.
