### ISSUE TITLE
When the code will be released? 

### ISSUE THREAD

**Issue by CBY-9527** [Serenos/DI-V2X#2]
Hi,

I am very interested to your work. I wonder when you plan to release the main part of the code. Thanks.

Regards,

**Comment by Serenos** [comment]
I'll release the code in two weeks. 



| |
Lixiang
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 3/21/2024 19:55 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [Serenos/DI-V2X] When the code will be released? (Issue #2) |

Hi,

I am very interested to your work. I wonder when you plan to release the main part of the code. Thanks.

Regards,

**Comment by wangsch10** [comment]
您好，您DI-V2X协同感知的工作非常棒！我目前的研究方向就是这个方向，对您的工作非常感兴趣，请问您什么时候发布代码呢？谢谢！

**Comment by Serenos** [comment]
已开源，感谢支持。

**Comment by wangsch10** [comment]
> 已开源，感谢支持。

感谢！（＾ｖ＾）
